
2021-06-12 02:02:42,764 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:02:42,779 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:02:42,779 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:02:58,978 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:02:58,993 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:02:58,993 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:525]
2021-06-12 02:07:18,966 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:07:18,981 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:07:18,981 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:08:21,483 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:08:21,498 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:08:21,498 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:34,669 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:34,684 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:34,684 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:45,723 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:45,737 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:18:45,737 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:526]
2021-06-12 02:23:16,367 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:527]
2021-06-12 02:23:16,381 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:527]
2021-06-12 02:23:16,381 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:527]
2021-06-12 02:31:37,657 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:528]
2021-06-12 02:31:37,671 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:528]
2021-06-12 02:31:37,671 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:528]
2021-06-12 02:39:26,101 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 02:39:26,114 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 02:39:26,114 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 02:40:48,716 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 02:40:48,730 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 02:40:48,730 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:529]
2021-06-12 17:23:53,859 INFO: errors [in e:\Udacity Full Stack Course\FYYUR\app.py:58]
2021-06-12 17:24:13,620 ERROR: Exception on /venues [GET] [in C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_collections.py", line 1008, in __call__
    return self.registry[key]
KeyError: <greenlet.greenlet object at 0x000001AFB0D305C0 (otid=0x000001AFB0CCA680) current active started main>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "e:\Udacity Full Stack Course\FYYUR\read_ops.py", line 15, in venues
    cities = Venue.query.with_entities(Venue.city, Venue.state).group_by(Venue.city, Venue.state).all()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 552, in __get__
    return type.query_class(mapper, session=self.sa.session())
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\scoping.py", line 129, in __call__
    return self.registry()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\_collections.py", line 1010, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\orm\session.py", line 4089, in __call__
    return self.class_(**local_kw)
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 176, in __init__
    bind = options.pop('bind', None) or db.engine
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 998, in engine
    return self.get_engine()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 1017, in get_engine
    return connector.get_engine()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 594, in get_engine
    self._engine = rv = self._sa.create_engine(sa_url, options)
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\flask_sqlalchemy\__init__.py", line 1027, in create_engine
    return sqlalchemy.create_engine(sa_url, **engine_opts)
  File "<string>", line 2, in create_engine
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\create.py", line 522, in create_engine
    entrypoint = u._get_entrypoint()
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\engine\url.py", line 636, in _get_entrypoint
    cls = registry.load(name)
  File "C:\Users\Rajpr\AppData\Local\Programs\Python\Python39\lib\site-packages\sqlalchemy\util\langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
